[package]
name = "rgbsc"
version = "0.1.0"
edition = "2021"

[dependencies]
amplify = "4.0.0"
strict_encoding = "2.0.1"
strict_types = "1.0.0"
aluvm = "0.10.0"
bp-core = "0.10.0"
rgb-std = { version = "0.10.0", features = ["serde", "fs"] }
serde = "1.0.152"
serde_json = "1.0.93"
