[package]
name = "rgb-schemata"
version = "0.11.0-beta.2"
description = "Collection of the official RGB smart contract schemata"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-schemata"
rust-version = "1.67"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
amplify = "4.5.0"
strict_encoding = "2.6.1"
strict_types = "1.6.3"
aluvm = "0.11.0-alpha.1"
bp-core = "0.11.0-beta.1"
rgb-std = { version = "0.11.0-beta.1", features = ["serde", "fs"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10.8"

[dev-dependencies]
chrono = "0.4.31"

[features]
all=[]

[patch.crates-io]
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "canary" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.11" }
aluvm = { git = "https://github.com/AluVM/rust-aluvm", branch = "v0.11" }
