[package]
name = "rgb-schemata"
version = "0.10.0-alpha.1"
edition = "2021"

[dependencies]
amplify = "4.0.0"
strict_encoding = "2.2.0"
strict_types = "1.2.0"
aluvm = "0.10.2"
bp-core = "0.10.3"
rgb-std = { version = "0.10.2", features = ["serde", "fs"] }
serde = "1.0.152"
serde_json = "1.0.93"
