[package]
name = "rgbsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify = "4.0.0-beta.17"
strict_encoding = "2.0.0-rc.1"
strict_types = "1.0.0-beta.3"
rgb-core = { version = "0.10.0-beta.1", features = ["base64"] }

[patch.crates-io]
strict_encoding = { git = "https://github.com/strict-types/strict-encoding" }
strict_types = { git = "https://github.com/strict-types/strict-types" }
bp-core = { git = "https://github.com/BP-WG/bp-core" }
aluvm = { git = "https://github.com/AluVM/rust-aluvm" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core" }
