[package]
name = "rgbsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify = "4.0.0-beta.17"
strict_encoding = "2.0.0-rc.1"
strict_types = "1.0.0-beta.3"
aluvm = "0.10.0-alpha.1"
bp-core = "0.10.0-beta.2"
rgb-std = { version = "0.10.0-alpha.1", features = ["serde", "fs"] }
serde = "1.0.152"
serde_json = "1.0.93"
