[package]
name = "rgb-schemata"
version = "0.10.0-beta.1"
description = "Collection of the official RGB smart contract schemata"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-schemata"
rust-version = "1.66"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
amplify = "4.0.0"
strict_encoding = "2.2.0"
strict_types = "1.2.0"
aluvm = "0.10.2"
bp-core = "0.10.3"
rgb-std = { version = "0.10.2", features = ["serde", "fs"] }
serde = "1.0.152"
serde_json = "1.0.93"

[features]
all=[]

[patch.crates-io]
# TODO: Remove after merge and release new version
strict_types = { git = "https://github.com/strict-types/strict-types" }
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation" }
bp-core = { git = "https://github.com/BP-WG/bp-core" }
aluvm = { git = "https://github.com/AluVM/rust-aluvm" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-wallet", branch = "fix/issued-supply" }
