name = "Simplest"
implements = ["RGB20"]

[TypeSystem]
libs = ["RGBContract"]

[GlobalState.Nominal]
id = 0
count = 1
matches = { RGB20 = "Nominal" }
type = { Ticker = "RGBContract.Ticker", Name = "RGBContract.Name", Precision = "RGBContract.Precision" }

[GlobalState.Contract]
id = 1
count = 0
matches = { RGB20 = "Contract" }
type = "RGBContract.ContractText"

[Assignments.Assets]
id = 0
type = "fungibleU64"
matches = { RGB20 = "Assets" }
aluasm = ["pdvs 0"]

[Genesis]
global = ["Nominal", "Contract"]
assigns = [
    { name = "Assets", min = 1 }
]

[Transition.Transfer]
matches = { RGB20 = "Transfer" }
global = []
closes = [
    { name = "Assets", min = 1 }
]
assigns = [
    { name = "Assets", min = 1 }
]

[[Script.AluVM]]
proc = "sample"
aluasm = ["noop"]
